const dishes=[
{id:"d1",name:"Paneer Tikka Masala",category:"North Indian",price:349,badge:"Bestseller",tags:["Medium Spice","Gluten-free gravy"],description:"Smoky paneer in a fictional tomato-cashew gravy, served as an illustrative restaurant menu item.",image:"https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=1000&q=88"},
{id:"d2",name:"Dal Makhani",category:"North Indian",price:269,badge:"Bestseller",tags:["Slow-cooked","Comfort"],description:"A fictional slow-cooked black lentil dish presented for menu and cart interaction.",image:"https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1000&q=88"},
{id:"d3",name:"Amritsari Kulcha Plate",category:"Street Food",price:249,badge:"Popular",tags:["Chana","Pickle"],description:"Crisp stuffed kulcha with chana, chutney and pickle, represented as demo content.",image:"https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1000&q=88"},
{id:"d4",name:"Meroza Special Thali",category:"Thali",price:449,badge:"Bestseller",tags:["Complete Meal","Chef Pick"],description:"Paneer, dal, rice, breads, raita, salad and dessert in a fictional premium thali.",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=88"},
{id:"d5",name:"Choley Rice Bowl",category:"Thali",price:229,badge:"",tags:["Quick Meal","Mild"],description:"A fictional comfort bowl with choley, basmati rice and cooling raita.",image:"https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=1000&q=88"},
{id:"d6",name:"Dahi Papdi Chaat",category:"Street Food",price:179,badge:"Popular",tags:["Sweet & Tangy","Fresh"],description:"Crisp papdi, yoghurt and chutneys in a colourful fictional street-food plate.",image:"https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=1000&q=88"},
{id:"d7",name:"Gulab Jamun Duo",category:"Dessert",price:129,badge:"",tags:["Warm","Sweet"],description:"Two warm fictional gulab jamuns presented as a dessert add-on.",image:"https://images.unsplash.com/photo-1593701461250-d7b22dfd3a77?auto=format&fit=crop&w=1000&q=88"},
{id:"d8",name:"Kesar Rasmalai",category:"Dessert",price:169,badge:"Bestseller",tags:["Chilled","Saffron"],description:"A chilled fictional rasmalai dessert with saffron and pistachio visual cues.",image:"https://images.unsplash.com/photo-1601303516534-bf4e6c0030ae?auto=format&fit=crop&w=1000&q=88"}
];
const themes=[{accent:"#7A2130",soft:"#DFC1C6"},{accent:"#8B5B21",soft:"#DCC9AA"},{accent:"#4E6B43",soft:"#C3D1BD"},{accent:"#9A4E37",soft:"#DDB8AD"},{accent:"#5B637A",soft:"#C6CAD5"},{accent:"#735269",soft:"#CDBBC7"},{accent:"#3E7069",soft:"#BCD4D0"},{accent:"#695D4E",soft:"#CDC6BC"}];
const fonts=["Cormorant Garamond","Playfair Display","Bodoni Moda","DM Serif Display","Prata","Manrope"];
const $=id=>document.getElementById(id),root=document.documentElement,reduced=matchMedia("(prefers-reduced-motion: reduce)").matches,systemDark=matchMedia("(prefers-color-scheme: dark)");
let themeIndex=0,fontIndex=0,colourLocked=false,fontLocked=false,selectedMode="light",filter="All",cart={},currentDish=null,orderMode="Delivery",selectedBranch="Meroza Jaipur",selectedOffer="Family Feast";
function money(n){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n)}
function hexToRgb(hex){const c=String(hex).replace("#","");if(!/^[0-9a-fA-F]{6}$/.test(c))return null;return[parseInt(c.slice(0,2),16),parseInt(c.slice(2,4),16),parseInt(c.slice(4,6),16)]}
function mix(hex,a=.64){const r=hexToRgb(hex);return r?`#${r.map(v=>Math.round(v+(255-v)*a).toString(16).padStart(2,"0")).join("")}`:"#DFC1C6"}
function applyTheme(t,i=-1){const rgb=hexToRgb(t.accent);if(!rgb)return;root.style.setProperty("--accent",t.accent);root.style.setProperty("--accent-rgb",rgb.join(","));root.style.setProperty("--accent-soft",t.soft||mix(t.accent));$("customColour").value=t.accent;$("customHex").value=t.accent.toUpperCase();document.querySelector('meta[name="theme-color"]').content=t.accent;[...$("themeSwatches").children].forEach((b,n)=>b.classList.toggle("active",n===i))}
function applyFont(f){root.style.setProperty("--display",`"${f}",Georgia,serif`);$("fontSelect").value=f}
function resolveMode(m){root.dataset.mode=m==="system"?(systemDark.matches?"dark":"light"):m;$("modeStatus").textContent=m[0].toUpperCase()+m.slice(1);document.querySelectorAll("[data-mode-value]").forEach(b=>b.classList.toggle("active",b.dataset.modeValue===m))}
function updateLocks(){$("lockColour").classList.toggle("locked",colourLocked);$("lockFont").classList.toggle("locked",fontLocked);$("lockBoth").classList.toggle("locked",colourLocked&&fontLocked);$("lockColour").querySelector("b").textContent=colourLocked?"Locked":"Unlocked";$("lockFont").querySelector("b").textContent=fontLocked?"Locked":"Unlocked";$("colourStatus").textContent=colourLocked?"Locked":reduced?"Manual":"Auto · 3 sec";$("fontStatus").textContent=fontLocked?"Locked":reduced?"Manual":"Auto · 3 sec";$("lockBoth").textContent=colourLocked&&fontLocked?"Unlock Both":"Lock Both"}
themes.forEach((t,i)=>{const b=document.createElement("button");b.type="button";b.style.setProperty("--swatch",t.accent);b.onclick=()=>{themeIndex=i;applyTheme(t,i)};$("themeSwatches").appendChild(b)});applyTheme(themes[0],0);applyFont(fonts[0]);resolveMode("light");updateLocks();
if(!reduced){setInterval(()=>{if(!colourLocked){themeIndex=(themeIndex+1)%themes.length;applyTheme(themes[themeIndex],themeIndex)}},3000);setInterval(()=>{if(!fontLocked){fontIndex=(fontIndex+1)%fonts.length;applyFont(fonts[fontIndex])}},3000)}
$("customColour").oninput=e=>applyTheme({accent:e.target.value.toUpperCase(),soft:mix(e.target.value)});$("customHex").onchange=e=>{let v=e.target.value.trim();if(!v.startsWith("#"))v="#"+v;hexToRgb(v)?applyTheme({accent:v.toUpperCase(),soft:mix(v)}):e.target.value=getComputedStyle(root).getPropertyValue("--accent").trim()};$("fontSelect").onchange=e=>applyFont(e.target.value);$("lockColour").onclick=()=>{colourLocked=!colourLocked;updateLocks()};$("lockFont").onclick=()=>{fontLocked=!fontLocked;updateLocks()};$("lockBoth").onclick=()=>{const v=!(colourLocked&&fontLocked);colourLocked=v;fontLocked=v;updateLocks()};document.querySelectorAll("[data-mode-value]").forEach(b=>b.onclick=()=>{selectedMode=b.dataset.modeValue;resolveMode(selectedMode)});systemDark.onchange=()=>selectedMode==="system"&&resolveMode("system");$("resetCustomizer").onclick=()=>{themeIndex=fontIndex=0;colourLocked=fontLocked=false;selectedMode="light";applyTheme(themes[0],0);applyFont(fonts[0]);resolveMode("light");updateLocks()};
const customizer=document.querySelector(".customizer");function setCustomizer(v){customizer.classList.toggle("open",v);$("customizerToggle").setAttribute("aria-expanded",v)}$("customizerToggle").onclick=()=>setCustomizer(!customizer.classList.contains("open"));$("customizerClose").onclick=()=>setCustomizer(false);

const body=document.body,nav=$("mainNav");$("menuButton").onclick=()=>{const o=nav.classList.toggle("open");body.classList.toggle("locked",o);$("menuButton").setAttribute("aria-expanded",o)};nav.querySelectorAll("a").forEach(a=>a.onclick=()=>{nav.classList.remove("open");body.classList.remove("locked")});
document.querySelectorAll(".reveal").forEach(el=>{if(reduced)el.classList.add("visible");else new IntersectionObserver((entries,obs)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");obs.unobserve(e.target)}}),{threshold:.1}).observe(el)});

const dishSearch=$("dishSearch"),dishSort=$("dishSort"),menuGrid=$("menuGrid");
function renderMenu(){const q=dishSearch.value.trim().toLowerCase();let list=dishes.filter(d=>(filter==="All"||d.category===filter||d.badge===filter)&&(!q||`${d.name} ${d.category} ${d.tags.join(" ")} ${d.description}`.toLowerCase().includes(q)));if(dishSort.value==="low")list.sort((a,b)=>a.price-b.price);if(dishSort.value==="high")list.sort((a,b)=>b.price-a.price);if(dishSort.value==="name")list.sort((a,b)=>a.name.localeCompare(b.name));menuGrid.innerHTML=list.map(d=>`<article class="dish-card"><div class="dish-image"><img src="${d.image}" alt="${d.name}, fictional vegetarian dish" loading="lazy">${d.badge?`<span class="dish-badge">${d.badge}</span>`:""}<span class="veg-mark" aria-label="Vegetarian"><i></i></span></div><div class="dish-copy"><small>${d.category.toUpperCase()}</small><h3>${d.name}</h3><p>${d.description}</p><div class="dish-tags">${d.tags.map(t=>`<span>${t}</span>`).join("")}</div><div class="dish-price"><strong>${money(d.price)}<span>Fictional price</span></strong></div><div class="dish-actions"><button class="add-dish" type="button" data-add="${d.id}">Add</button><button class="view-dish" type="button" data-view="${d.id}">View</button></div></div></article>`).join("");$("menuEmpty").hidden=list.length!==0;document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addCart(b.dataset.add));document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>openDish(b.dataset.view))}
document.querySelectorAll("[data-menu-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.menuFilter;document.querySelectorAll("[data-menu-filter]").forEach(x=>x.classList.toggle("active",x===b));renderMenu()});dishSearch.oninput=renderMenu;dishSort.onchange=renderMenu;renderMenu();

function byId(id){return dishes.find(d=>d.id===id)}
const cartDrawer=$("cartDrawer");function openCart(){cartDrawer.classList.add("open");cartDrawer.setAttribute("aria-hidden","false");body.classList.add("locked")}function closeCart(){cartDrawer.classList.remove("open");cartDrawer.setAttribute("aria-hidden","true");body.classList.remove("locked")}$("cartToggle").onclick=openCart;$("mobileCart").onclick=openCart;$("cartClose").onclick=closeCart;
function addCart(id,qty=1){cart[id]=(cart[id]||0)+qty;updateCart();openCart()}
function updateCart(){const entries=Object.entries(cart).filter(([,q])=>q>0),count=entries.reduce((s,[,q])=>s+q,0),subtotal=entries.reduce((s,[id,q])=>s+byId(id).price*q,0);$("cartCount").textContent=count;$("mobileCartCount").textContent=count;$("cartSubtotal").textContent=money(subtotal);$("cartEmpty").hidden=entries.length!==0;$("checkoutButton").disabled=entries.length===0;$("cartItems").innerHTML=entries.map(([id,q])=>{const d=byId(id);return `<article class="drawer-line"><img src="${d.image}" alt="${d.name}"><div><h3>${d.name}</h3><p>${money(d.price)} · Pure Veg</p><div class="qty-control"><button type="button" data-minus="${id}">−</button><span>${q}</span><button type="button" data-plus="${id}">+</button></div></div><button class="remove-line" type="button" data-remove="${id}">×</button></article>`}).join("");document.querySelectorAll("[data-minus]").forEach(b=>b.onclick=()=>{cart[b.dataset.minus]-=1;if(cart[b.dataset.minus]<=0)delete cart[b.dataset.minus];updateCart()});document.querySelectorAll("[data-plus]").forEach(b=>b.onclick=()=>{cart[b.dataset.plus]+=1;updateCart()});document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{delete cart[b.dataset.remove];updateCart()})}
document.querySelectorAll("[data-order-mode]").forEach(b=>b.onclick=()=>{orderMode=b.dataset.orderMode;document.querySelectorAll("[data-order-mode]").forEach(x=>x.classList.toggle("active",x.dataset.orderMode===orderMode))});$("heroBranch").onchange=e=>{$("cartBranch").value=e.target.value;selectedBranch=e.target.value};$("cartBranch").onchange=e=>{$("heroBranch").value=e.target.value;selectedBranch=e.target.value};
$("checkoutButton").onclick=()=>{const lines=Object.entries(cart).map(([id,q])=>{const d=byId(id);return `${d.name} × ${q} = ${money(d.price*q)}`}),total=Object.entries(cart).reduce((s,[id,q])=>s+byId(id).price*q,0),msg=["Hello Ajay, I am testing the Meroza Kitchen demo.","",`Order Mode: ${orderMode}`,`Branch: ${$("cartBranch").value}`,"","Demo cart:",...lines,`Subtotal: ${money(total)}`,"","No real food order is requested. I want information about a restaurant ordering website."].join("\n");open(`https://wa.me/919929562585?text=${encodeURIComponent(msg)}`,"_blank","noopener")};updateCart();

const dishModal=$("dishModal");function openDish(id){currentDish=byId(id);$("dishModalTitle").textContent=currentDish.name;$("dishModalCategory").textContent=currentDish.category;$("dishModalPrice").textContent=money(currentDish.price);$("dishModalText").textContent=currentDish.description;dishModal.querySelector(".dish-modal-media").style.backgroundImage=`url("${currentDish.image}")`;dishModal.showModal();body.classList.add("locked")}$("dishClose").onclick=()=>{dishModal.close();body.classList.remove("locked")};dishModal.onclick=e=>{if(e.target===dishModal){dishModal.close();body.classList.remove("locked")}};$("dishAdd").onclick=()=>{dishModal.close();body.classList.remove("locked");addCart(currentDish.id)};

const offers={Family Feast:{label:"FAMILY MEAL · DEMO OFFER",title:"Family Feast",text:"Choose four mains, breads, rice and dessert through a fictional bundle flow.",price:"From ₹1,499*",image:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1600&q=88",ids:["d1","d2","d4","d7"]},Pickup Treat:{label:"PICKUP SAVING · DEMO OFFER",title:"Pickup Treat",text:"A fictional pickup-only saving designed to encourage direct restaurant orders.",price:"Save 12%*",image:"https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1600&q=88",ids:["d3","d6"]},Sweet Ending:{label:"DESSERT ADD-ON · DEMO OFFER",title:"Sweet Ending",text:"Add two fictional desserts to eligible family orders through a simple upsell.",price:"From ₹249*",image:"https://images.unsplash.com/photo-1593701461250-d7b22dfd3a77?auto=format&fit=crop&w=1600&q=88",ids:["d7","d8"]}};
document.querySelectorAll("[data-offer]").forEach(b=>b.onclick=()=>{selectedOffer=b.dataset.offer;const o=offers[selectedOffer];document.querySelectorAll("[data-offer]").forEach(x=>x.classList.toggle("active",x===b));$("offerLabel").textContent=o.label;$("offerTitle").textContent=o.title;$("offerText").textContent=o.text;$("offerPrice").textContent=o.price;$("offerImage").src=o.image});$("offerAction").onclick=()=>{offers[selectedOffer].ids.forEach(id=>cart[id]=(cart[id]||0)+1);updateCart();openCart()};

const formModal=$("formModal"),enquiryForm=$("enquiryForm");const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);enquiryForm.elements.date.min=tomorrow.toISOString().split("T")[0];enquiryForm.elements.date.value=tomorrow.toISOString().split("T")[0];
function openForm(type){$("enquiryType").value=type;if(type==="Table Booking"){$("formVisualLabel").textContent="DINE-IN · DEMO";$("formVisualTitle").textContent="Plan your table.";$("formVisualText").textContent="Capture date, guests, branch and occasion in one clean flow.";$("formLabel").textContent="TABLE BOOKING · DEMO";$("formTitle").textContent="Book a table"}else{$("formVisualLabel").textContent="CATERING · DEMO";$("formVisualTitle").textContent="Plan the celebration.";$("formVisualText").textContent="Capture event date, guest count, venue and food requirements.";$("formLabel").textContent="CATERING ENQUIRY · DEMO";$("formTitle").textContent="Plan catering"}formModal.showModal();body.classList.add("locked")}
document.querySelectorAll("[data-open-table]").forEach(b=>b.onclick=()=>openForm("Table Booking"));document.querySelectorAll("[data-open-catering]").forEach(b=>b.onclick=()=>openForm("Catering Enquiry"));$("formClose").onclick=()=>{formModal.close();body.classList.remove("locked")};formModal.onclick=e=>{if(e.target===formModal){formModal.close();body.classList.remove("locked")}};

function openSimple(eyebrow,title,text,msg){$("simpleEyebrow").textContent=eyebrow;$("simpleTitle").textContent=title;$("simpleText").textContent=text;$("simpleLink").href=`https://wa.me/919929562585?text=${encodeURIComponent(msg)}`;$("simpleModal").showModal();body.classList.add("locked")}
document.querySelectorAll("[data-open-track]").forEach(b=>b.onclick=()=>openSimple("ORDER TRACKING · DEMO","Track preparation to arrival.","No order is tracked. A real version can connect order states, rider details and notifications.","Hello Ajay, I want an order-tracking feature for a restaurant website."));
document.querySelectorAll("[data-open-loyalty]").forEach(b=>b.onclick=()=>openSimple("LOYALTY PROGRAMME · DEMO","Bring customers back.","A real version can connect login, points, rewards and order history.","Hello Ajay, I want a loyalty and rewards feature for a food-ordering website."));
document.querySelectorAll("[data-open-business]").forEach(b=>b.onclick=()=>openSimple("FOOD WEBSITE PROJECT","Turn the menu into an ordering journey.","Connect menu, branches, cart, payments, delivery and admin management.","Hello Ajay, I want a premium restaurant ordering website like Meroza Kitchen."));
$("simpleClose").onclick=()=>{$("simpleModal").close();body.classList.remove("locked")};$("simpleModal").onclick=e=>{if(e.target===$("simpleModal")){e.currentTarget.close();body.classList.remove("locked")}};

const locations=[...document.querySelectorAll("[data-location]")];$("locationSearch").oninput=()=>{const q=$("locationSearch").value.trim().toLowerCase();locations.forEach(c=>c.hidden=!!q&&!c.dataset.location.includes(q)&&!c.textContent.toLowerCase().includes(q))};document.querySelectorAll("[data-branch]").forEach(b=>b.onclick=()=>{selectedBranch=b.dataset.branch;$("heroBranch").value=selectedBranch;$("cartBranch").value=selectedBranch;openSimple("BRANCH SELECTED · DEMO",selectedBranch,"The selected branch can control menus, availability, timing and delivery area.",`Hello Ajay, I want branch-wise ordering pages like ${selectedBranch}.`)});
document.querySelectorAll(".faq-list button").forEach(b=>b.onclick=()=>{const o=b.getAttribute("aria-expanded")==="true";document.querySelectorAll(".faq-list button").forEach(x=>x.setAttribute("aria-expanded","false"));b.setAttribute("aria-expanded",String(!o))});

function setErr(input,msg){input.setAttribute("aria-invalid",String(Boolean(msg)));const s=input.closest("label")?.querySelector(".field-error");if(s)s.textContent=msg;return!msg}
function validate(i){if(i.required&&!i.value.trim())return setErr(i,"This field is required.");if(i.name==="phone"&&!/^[0-9+\s()-]{8,18}$/.test(i.value.trim()))return setErr(i,"Enter a valid phone number.");return setErr(i,"")}
function validForm(f){const fields=[...f.querySelectorAll("[required]")],ok=fields.map(validate).every(Boolean);if(!ok)fields.find(x=>x.getAttribute("aria-invalid")==="true")?.focus();return ok}
enquiryForm.onsubmit=e=>{e.preventDefault();if(!validForm(e.currentTarget))return;const d=new FormData(e.currentTarget),msg=["Hello Ajay, I am viewing the Meroza Kitchen demo.","",`${d.get("enquiryType")} enquiry:`,`Name: ${d.get("name")}`,`Phone: ${d.get("phone")}`,`Date: ${d.get("date")}`,`Guests: ${d.get("guests")}`,`Branch: ${d.get("branch")}`,`Requirement: ${d.get("message")||""}`,"","This is a website enquiry, not a real restaurant booking."].join("\n");open(`https://wa.me/919929562585?text=${encodeURIComponent(msg)}`,"_blank","noopener")};
$("priceForm").onsubmit=e=>{e.preventDefault();if(!validForm(e.currentTarget))return;const d=new FormData(e.currentTarget),msg=["Hello Ajay, I want a food website price.","",`Name: ${d.get("name")}`,`Phone: ${d.get("phone")}`,`Restaurant / Brand: ${d.get("business")||""}`,`Website Type: ${d.get("type")}`,`Details: ${d.get("message")||""}`,"","Reference: Meroza Kitchen Demo"].join("\n");open(`https://wa.me/919929562585?text=${encodeURIComponent(msg)}`,"_blank","noopener")};
